sudo: enabled
language: bash
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: lJW1to+bJe0kfHB72oiXcMHoIdBUUYcRL0rlfLH7Y3Lld1Y4AStDsgbaFT0+sdg7Qi1L2Z3Yemb4qVnwjcejbQJVagJZQZDL3kYs8LCsjNIqW3XErT3RGY1ixeYK5qN/S4u5YushSYEAU21U2G00kY5+kKMFpBZfJz5g70E7ILlPgCO6i1uz5AO9TK2ggMmDfU7Z7Vm9/WX5VatrjLPhiBZgnCZvKKjp6TnxD2ZjNh8tBUs2+G9gWYf1/Mf26pDWaDpxdEF1CtE9/BWDICb+e8H/Xk4hleozIYBDPMF2gcePMsd2eUmMLZ8Cth1K0clBpxh4E8AKczKGF+aSTK1OF0nxFs+4KB4IkQ/b+PcVwRsGY3rP+77uf01DiqK6I03lnM6+wzsXjMKW5PaEwmnc7Gv7b4FilrSN/RZlTJku2znVp8vLOIE84kgJmfjgqkM/x7jCY3OHnN4Awbqqhz29g1D3b8VZmWoEAr+pXdgS+LCGhvv3Yn1rrpqTGQzn9PDK8TioQwcUqDsgxnq8JXhnsnWSb9Mc4+6SdI7NGGrrN+wiN22laoF2K76vbYnR527XRx9+HkhBowu6Xda6eJLeDN4NC+MGHvNRVH4gumBSN06V0qxjX4db6TCI/mcB6b2Xg/IbbVJEV/Tbe4appXCjfnjRfOzebd2jMjXDR0XGANI=
  - secure: XhZM7UeW/2eaSEjkcSvZV1mMALO2EwG15ahMjldpjGWTBnbPqLQywn61s8vj0+zQuuWTwVXjdE5sCM07CfaiLR/TMKvWIk1iXNoLKuaPern805rOrQY+/DxY/PwPdnpmc42bxwHkN12o0d8sq5u15gS0mCbSa4AHWYlWd+TgdPNJP5qPQIqqiLuvIiZxg7ShQiEwYjXRyLiM6TTTdK/9I8V95PyrfFEdPih2Etiq4hTTulTACctNERjUtm3x+iq6MN2Vpo7qguleTeC4GUlMQ2L8zpE50x24hip9/r1b4U2aPaZ6BIbZPUepZtFlM9C5gIxITo8oe2U+mFrGznajA1jHEHWVandhRzZw8gyWA1Nmp23HSA8g0ceEUwVAB5PY/PiOU5apkHeRfka9Fj2Vqhk6E67eDea6F3kI6L3wHT1sxUcN9uIcjrhm5XR7UefqSRTm0si/7kWZy38Z1ghi8cVLgF2iNA1qjCIhrMc1s9jEIYN8TQr3HCKW+DpmXgOIFnQvOeDx9VtB6gSJ/zZK+GIW07IPm/adDN76yWHphOvviTLXvpwpaNeAtH7tgvF8dSASL1348bC2hNqOJpO4+Fki0SfMDCRxHzzA+/emIXeVjr/6JKw74A0dMLM2CrLerznr/wDlMD2oitU3Lr02Spp0MPS+8KVpnp1VLDFO4/I=
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
