sudo: enabled
language: bash
services:
- docker
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
env:
  global:
  - secure: ZueZbfV+bQUpoX6W+0N563P0jX2PP94zN4uPsi8U0RzE6tBZdlOSocgx7ek9E2W3b6JatQkE+A1c8RPSek0Xn3N/mk3ug4fqeLo6DXjY3pUIKyd1zlu0UXrBjFcYshEsEi29MtGS81NtojqMdsu50M6cvuxu5ulKibI7/ZbUZ56WLKTpbg3i4VdtbF36uJpnDI6/ps2tzH+UaAxTuU2cilxGLgQOMKBt9gjxEazB5IWNWIRUMOTiQihmKCL1HHSdjpB1HcageE9lSFkbSg2kdUUzUiMz/KAyj7bBazRd/v1Qy+EkN89NSf5rzv85EFppLRJSeQQaUjdUIj6Cs5a58i1B0EF5Wce1rouZ5LXfPdAlt8eVGYjw6U7QKrTE9JuPb4JC8skP/09PAp8883RJ9Pb6vfhELKjBz+RyTGFuoIMwmChIXA4UaX2gNI6hA1V1v4MuiXIFE+wpsIiGjI6tgK+xEp/KNiujcGWWY6x2ho6MRdjzBaliUXXjbKdI2ZEL+PxVDfjHqpbt2gPglnx9ts4WZ5815owf15XvlRkO0pME3Wq1Wg9hQvDONhJyd00gRl7v9RCOWU9b9gy1zLZ+HQFXiOCKP8l2e2UXIcQ3mEv1TwJQyLsxuVjHI7rF5stX3Q2T8lWsHir/53iMD4HNDu/sR9s5Cy3gnAAyTc5foms=
  - secure: jPFventyaivu382/EsGFqwJkortrneV+6J+T8GNoobfR+3J32ZnoI2awywWHSuL0jhUW/AoDN+AhjhsoRa6ZHCgMFzS1+/pRE4ZEKCymBM7lH5/6hJqnTWcUs7siDHilcnDshekpugfXMrrIhzx9GTiZapqrDDZOvR7cIGyxbE+KLkcIjv9enSnU35uAotO2/BbXzmpzV+OhZMpw6/UH/vTuCfVrqRrrEl6ey742t1EKt1Juq4EjVkLvgAZiQIRjmFsKFzAJceYhORsa6XcTJAZNZwzBNzPaPJcYmdMVG/+j9FGgjESY6l/qkRusCQ2tzFQ7RQzHhk8SB3GyFoPclWRJ+i/uW3ptVkDdYGS0OnYVlCJjv8l9iiaIRvx6jNEnWubi5hjKhcYSZ3zNgOSgDRl54r4Z94De367nFOXbY4PifdB1RVyJbHOlRr3AB31sJhcrb1R5y8BUkTutteD98ZhEKOSSs6NQBLgEF8v4VkjcEaEIYVFXJLlRb2+6h9qt40cRCTKAoceh4FIfGU+ab+l8w25x3FlWS4DudbUKIeD1MNSi+LQyToJZdTuFKC3OdFvUB9cRjvt+2/6t1p0LVwPsfrpb3s9F27CRczMNdI3FwzerCC5EAYPIKEEJDPuodvKxcwAbq4CXI9wbObIqrnUAhIsQlGnuXMYVL8bcLkI=
