sudo: enabled
language: bash
services:
- docker
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
env:
  global:
  - secure: BImkmnlSSNST0z08Y5XOBYcUWmDUccDjPAqJhfR4vBIgRz1RRN2+SjJjnIBAXuxoePXVK6gcG3CciKxEsvsgj2t0wikYd6wNbDyfzvQa+pbE4dbEBqX/JrTHJoWR4eSPThL++jFPwTlOe6zLGI4ZXyRCN1QEUYF2nT9QWPaSc3arZOCIQ14mnxAC53ssqMzY8/yiqTux6be1NMZFEWcCXnAm86Rc5FqgDMa0GtCDHp5Ro/XiUTMZxvBOdSWyXhj4RKW52U7Bz6jGLlJ2WC6yVe0n2p9srYJPlxj+7/w0vzc49ztOCX5rNMeVb4PCtX1vDSbaKchy43lkmi1AHJPyeY8EmVitdVG0BqGwPLEp9e3DgCvSSVhel1ptKPgKkxQuk0ZtnF44wHVqGnsLp3xgLQoL2JQMeB93PaVY8GebQsrdUAivjXBjGdSLp05isEI8bagVilgflAYkfZjjpfO207wzm7Q9ZnEjd258QreW4CEVHP3mZShbvSqnffIOG3EfGFamTeVWI5pzMt1jOWd4M/azWjqYizzMw2cYk5GH94XJZ8j1cR/hj4Y2gwFLU0CYgHkmqnA1A2yedNo0s2u9yb+j2avs+OaI/IHGNKqxatro9FfJRtsdiJzkyZACtdcjoGgWeDQ95Y3Y0gbRLAGprhxSvUHL4UaTcEuHVz8KHao=
  - secure: ZqgpXFeiVVlz56D7u49eRrqw+TI2bbCQvSEb5BF7xQBSyf/8BLFW2TU5G+GNMtphIFcmrFdLt3DkpmIqSQY81YcW50efgv7PmFDmCBfdRmEemy6o/KM00Ke1zmM6GtDEVTTbVLU74Ob5rGvfB6XyzbJgUSHdppsX0E4J90PNjUtQlFDKNZBOi5ua0qp1C9KOmtHVan8htrYYVkEV2TrFbtWg8PBBsTq/zNrIKyvC8bUS44H0wUnfgxftr8AJ3rg2QMUz+/WO28jdg7/XDtX9EccErpy/CP3V7+rGkIHvhyghFFqZYIoXghxDNGX7jlHX2HW6tVlQQ4gWaBpusz5Oo5eiJeOgovYv7zlQRPHCSBEHq4rscK7krpNkvDycpbJcDTaQxNuUS/Hot6Q9qX+D7xbXgWVwQ5YSY+pZaQ5y45l7VVa0ifqepPibu5E/xxbdioEfah/+PKYk9vwQXJYwhgs4KRxhz9dN0QUZRvGVwyXF/krvqovXu3CTIWtfwXfSXqkzmnUBnwoomXOpNXJ+Ymy/pJ8t0pauxRNKhRDlSJmTJqQz6h9STfARdwDCnRBfciFSF9Gd61DH5NKsO3HIsBx0apgoxTSp8e/jvkyCa40ZSmdlQ1KioExi1zFp2n0HcETPTs7zqw4CsdmOpfVl0GkupzMFnt0cDaRdz+1szlw=
