sudo: enabled
language: bash
services:
- docker
env:
  global:
  - secure: OJ5w/L+11ARNzO4Cp59h8YAuJyWw721Qw0NTEcHmw10veqfBVmaN2STt2m03wjaC7WT1PDm4jkrUHulQVKysO+TyHFerSJNjprY/jspFrAd8Y0oEduDX9bCAKhLCSoSB07CR3x0AJxGP+hgAcWKiVNKIUmZNHFICnDYSaHYYt3p9ohDpjUEvQmOi0vbSpFKE9ZLuzjX6FZ5S8Jn7nBqlyjvnyObs6GQsuO1oytqCyY8CJpx5kx9r3C7XqioYAJlNE1fXPlM7smDiqq4165OQb1hxMIs8vUEKvko/YVKeeZvGnZFTUqaLuFFZyBRoqOWIIjyz9Z+P7iRH+MgMnIzxTuCDk9d08nyebF+utgR54XRIIMOi29nH2RpDk12aNpCeOpm/k5k1ZUxZYT/d+80R61j3tWLX0doS4G8slTkYqXdB+AKTUlj88fQ21OB3iZhtS95V1Dhn4WoRVUWX6mUpqWpz2my61YWZ2sAqnReUWB8aLSzU+IydVYsKFIADDScfrG2zdMM/PTiQp19k4eKZVfo4PooxAK8TvsjbSToCWNAoQ2MaMfa4gsEwIc2LFNFcDvIRfEgi6z0URWNyieUATbOeG1LDh5FAi0uLmvy11eNDnMN6QzF5V0f+5HuzOsbx9tAbVgIlPKFqlMa0YKVb4J9EKqiDHgfP44A0PveesIQ=
  - secure: b8qpk+dlt7Xj6/NylWtpPGFuy1uh2+9SeT7aLp/s5cTMCnKZxABJajjtWkKsl3QLlf79dN+f19kwaYq+9ZS/UbH84NI5L1TEXlr5T6Af+Big/5zo89j3SaVwq27FCakI/YRZ0YywdcHYgLTGv5F7YpTfg3w8T14NdmJwhAf8HnAvGy3exai3PKXmoBt/b72e3DuUSyVqzrb48KDi7CldEZT6u1SAHExt50HOwaBtkigPIB1KD/04wTd+85nqW1AtRxxd8apuH/jbBSIeNTIF5mn7SgY/nXUOuTUMgsb3xUC6I5//hb5Lx3+jMkUHTz0rqoaZacOyNpZftjAprx15kiUMAtFV0I6fUtDA6Cso74cAVOKDKMmKTxmQd5PMH8eSnu9LW7snhVFF5rXa73TxZokXiPwq/XAs+kEr+NEaEurrGcGq3PCyWwMjdnxCZ8gkMbSqIjEXZ/Ixo9OEA/YROeRfkuOC2ZwWphVfvY/ICUBaPaFDFHqDX/zOEt5nr44pIxX28EallV+GFKzeXVl6Ua0P3j+HG3Y8+CkxI9w/JO1+KIqjuZPfX5zoDOW7Fu4UoUpdcGZE9G3l2nLQtEmwmNgsJIUMjSiJeoT0aySTfQqY+RG6qZ0GZ3ARpIgWspkJ0JX66f82bJ9J7lBt6KBEvpmgWsbgYjOQ4Bk24NwRz4A=
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
