sudo: enabled
language: bash
services:
- docker
deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
env:
  global:
  - secure: RKW7fqgqeh5gx9LnlXx75msFqdkUhV5goZpnmh5FUu5SvRXFSKb0caaIFupm4oBHSoJfaA8elIwrKEbEXdnzhtfoTjVNs7U7qeL99gLq2U+Vt8Ro/uw7Y5GupjNUzG8fpI5otsqoGghvELoXVX4st1p3p0pHRVz/9rA3cAOz29cLtsgwjotp75hR9VWsOHZGPy2CU+jJ7VP6ItA4BOm79wzDdiienK8Se159whnxQtCrkgE6DCYDUtUbIMBMzXzQ/H/QwOQk6yOyUBqEnxJdq4ER3M+cO0/3mACuTJV7TvlkLfh0r+R1KSirKWl1GlqTAMXkRaz5bynKMlWpQDFqermtsrfc7RkzoljjHBlRHaB2u2wJvyBGm4BbXJ/4fX0eDOPBuETkfR6VLGZ4XgYU5yEFwRilvvON0eg5p6rU2cIcnJtcLwjg2N+TNSSmC0zRugXJnH+mSi4ZCFmKJD/Gqy2xIsV3BfKcqChC5XCExkIfJTtCGmFN+zXIyN1J6KD88KBX0tASHNIPdCX8pFptt8q7itjGKcGaMRvzS25PbM4lSBDaZ/co35mngsXp9GYMeDO3hEhuqJri0c1X1kdx+6jsecG6tTFaA49FJTXz3jesC10ZMzo8+GyCJVF1vUVaDAzpcDGcBGu4pTIrPIw3J8AqH0flPT6FZd6/3kx5JYQ=
  - secure: o9ov/r9iwc+5jWMF0jG58gu8Giwg267Aj6lsjJi4GMm7PjymGTLQnZ6y+VdghB6PEuJkBuEPeAl1Y3usbyhs+eI0+TbHxIUH+YWTrOMNJhom3i41xol7lYAQKdtHuWamPfHgs62XlPXzO3rdIJoakKTvlBpwPKmfBgMapGQzRaNdgG8ixip+tOeiaDD9Kk079xWJiMilYnj+czxOKKhyErFDbUpGYzpaQU1iRvZGRGoePh0lmXoHr7/4virSA+3uUdigC27+67se/bmaC5vnSaL8tSC+45Q46yclost1ElU7QIEzZFt0YABJU1rFWDwP8DsSAdniNCieWncCpjEPMuLKkeWBGMNCEoCrog+9onSujFbJP/TR1azQZBLV5yjojadUnq77ydIv40nzNTzf2Ng7XMj+VPDh57U6tpSJf62t/qVpGvEoZKMpWqi8yxKdrqyoIwzL6EdN+w6jbuXD6m7TIEMZciUWp/dtK51+S+xjMI8Spfht38QGh0TbAckTMwSTxCeJZy21wBAZ0LKxRRQGdTfCGKwV2cAap2EycFBnquIErmOimZRrrzreXZtPVbdgp9nFmnAf3ISI+zd0/a5RjMCx344oNAaObzXTxUAeT54lTzMWivS809U1Y9WMbwxtj5KqUoN7BgALhcfjInjoKpoVTdrzaztrjrrtpK0=
