sudo: enabled
language: bash
services:
- docker
jobs:
  include:
  - stage: build base
    script:
    - "./build.sh base-notebook-gpu"
  - stage: build minimal
    script:
    - "./build.sh minimal-notebook-gpu"
  - stage: build scipy
    script:
    - "./build.sh scipy-notebook-gpu"
  - stage: build deep learning
    script:
    - "./build.sh datascience-notebook-gpu"
env:
  global:
  - DOCKER_USERNAME=bswrundquist
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: gDwkXIYiQfYRWqc9F38tQXx0Zrgi95FcaOLWGbHgNYmXJd2rd2ctNJA6IfzINfl0v44BI6T17oCcSplyFLiB7HVdg7nM6XHQJN7cQhgZBfHIpN1nQKripFCyAdHmqurxPGR2gt8SaCVH78JvBUt4Ia1WxyC5oA2vYCWYCvF1duK8qO72+iCQfXTjCqT85YI5ScawGKiGBcPfWi/wbvNL7k8q+R0YO47kSGsYme/2M1g8cvzi44InQhWXnayFarTL4SVUpDvACdo3IczzVqXbGI8bcVLDsfEbVlgERItdJiq1aHTKABqlPNBScXC/lJl29mo9MlnAh1+zDLlFD2wKPEMYtqRyM2O9vr/tIrOH9pu+rYo+tEY1SmHqzdNfkp/ART1/SZwb1xWEHYhG4AHIBPjjTCD+ZFhdinMzOsM3Pe2vR8jgUgGo7CxuNbWYZ2HoSqM7IKimZjO+PnLSl+QwYJcohATZrBAMtYfd/wH7uYJBY4wgp3Dr8nWFJr3bQ1H3W/SlgyiHZWnFBUtuylvjfGZOj4CZnMmJ4D4hJMBwUa35zYL5xY2ajJt7q4NIfJBmuiTxBRYb164+BpJIWo/I548bJ2lZH4NxPNtHiK2xWTBj2KtVN3YntSZQzauk3MT81farZKd0bnROZnTqkRzWA86+lt5BJ6Z5JugCKvSPwW8=
  - secure: fQ2glhKgiCiHM2bwVZP5tnY99ZCs5QbmO5Ln9QYmMaeNvi0LrfTpG0TiWodE7DikmWuTvykBexJeWWTEUSkp9YG2LJ5Wz1bBPPJJqA2Id+xh1iUECfxPGK0PX32FcQ5wzU6KoTl41LOw6P9OizdcfRmuKw9LtFuLMsO5uiTnXX8ARjiOkUa+vdkD1Rwi2w2XpzH7TUWCYCXprpNefZlC0hnoOqP59R5IpoXrFhL+YRyhaBPhOy4Y5V/dFJ0b4+O4wWgeROdF7QBW4JacmmJTzJM7uIZalagbPDuzMjXs+THIeJfVcdFOnO1/dUwJJcaH2NVqLHptxXTQoBFmhrFGC6UrPEEcHmhMGyv0d4KU6gauTQ8w0M5BVrw8dIPOcIIxkKOZfIW7W+IcixvuyaKFhe0vLcmAD5TPaZtxF13p7Gn6HgVrE0+lEOvGt9rdCxjJLQOMP08V80BFzaYLtLhr8TUXymS/L4ea7ctrHOMymKIVdoUjDgY8vEBXE09lsbViOic1iyrTNMDoeeNobxpvpd0TUixb4DFn9fs6+erW7ZcehvRXtzS+HNq94e0UahyzmLEtmv4eeQSGU5XwcozD/iH1fmCSOGmD0YEyavd94f0qZBvmKHwbr6ypemvRvkQX1fpS2W0eWykZ2qv9vHdCuDIBqDKQkvCCqnoRwjNMHok=
